<?php


/**
 * Implements hook_flag_default_flags()
 */
function flag_application_flag_default_flags() {
  $flags = array();
  // Exported flag: "Flag Application".
  $flags['flag_application'] = array (
    'entity_type' => 'node',
    'title' => 'Flag Application',
    'global' => '0',
    'types' =>
    array (
    ),
    'flag_short' => 'Apply',
    'flag_long' => 'Apply for this',
    'flag_message' => 'Thanks for applying',
    'unflag_short' => 'Remove application',
    'unflag_long' => 'Remove your application for this from this site',
    'unflag_message' => 'Your application removed',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'weight' => 0,
    'show_in_links' =>
    array (
      'full' => 'full',
      'teaser' => 'teaser',
      'rss' => 0,
      'search_index' => 0,
      'search_result' => 0,
      'token' => 0,
    ),
    'show_as_field' => 1,
    'show_on_form' => 0,
    'access_author' => '',
    'show_contextual_link' => 0,
    'i18n' => 0,
    'api_version' => 3,
  );
  return $flags;
}
/*
* Implements hook_flag_flag
*/
function flag_application_flag_flag($flag, $entity_id, $account, $flagging) {
  krumo('flag');
  dsm('mjaa');
//  dsm($flag);
  // krumo($entity_id);
  // krumo($account);
  // krumo($flagging);
}
