<?php
/**
 * Implements hook_block_info().
 */
function block_module_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts here'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
// Retrive Data Code
  function block_module_contents() {
    // Today's Date
    $today = getdate();
    // Date a Week Ago
    $start_time = mktime(0, 0, 0, $today['mon'] - 2 , ($today['mday']), $today['year']);
    // Get all posts from past 1 week
    $end_time = time();
    // Database Api for data retrieving from Database
    $query = db_select('node' , 'n')
      ->fields('n' , array('nid', 'title', 'created'))
    ->condition('status', 1) // shows only published nodes
    ->condition('created', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC') //Most Recent First
    ->execute();
    return $query;
  }
  function block_module_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();
  $count = null;
  switch ($delta) {
    case 'current_posts':
      $block['subject'] = t('This is my custom block');
      if (user_access('access content')) {
        $result = block_module_contents();
        // Array to carry items for block
        $items = array();
        // Itrate results and form links
        foreach ($result as $node) {
          $count += 1;
          $items[] = array(
            'data' => l($count . ' ' . $node->title , 'node/' . $node->nid),
            );
        }
        // if no results since last week
        if (empty($items)) {
        $block['content'] = '<b>No Data since Last Week</b>';
        }
        else {
          //Pass data through theme function.
          $block['content'] = theme('item_list', array(
            '#title' => t('Syndicate'),
            'items' => $items,
            '#prefix' => '<p>',
            '#suffix' => '</p>',
            '#markup' => t('Nodes are : '),
            )
          );
          $block['subject'] = t('Total Nodes are : '.$count);
          dsm($count);
        }
      }
      //   break;
  }
  return $block;
}
