<?php
/*
*hook_menu Implementation
*/
function crud_data_menu() {
    $items = array();
    $items['crud'] = array(
        'title' => 'Add New Friends',
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('crud_data_crud_form', 2),
        'type' => MENU_NORMAL_ITEM,
        'access callback' => 'user_is_logged_in',
        'menu' => 'menu-user-links',
    );
    $items['cruds'] = array(
        'title' => 'Add Friends',
        'access callback' => TRUE,
        'access callback' => 'user_is_logged_in',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('crud_data_crud_form', 2),
        'type' => MENU_NORMAL_ITEM,
        'menu-name' => 'menu-user-links',
    );
    $items['cruded'] = array(
        'title' => 'See Your Friends',
        'access callback' => TRUE,
        'access callback' => 'user_is_logged_in',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('crud_data_select_db'),
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'menu-user-links',
        'file' => 'demo_friends_show.inc',
    );
    return $items;
}
/*
* hook_form Implementation
*/
function crud_data_crud_form($form, &$form_state) {
    $form = array();

    $form['name'] = array(
    '#title' => 'Name',
    '#type' => 'textfield',
    '#size' => '30',
    '#placeholder' => "enter your name here",
    );

    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Start',
    "#submit"=>array('crud_data_crud_form_submit')
    );
  return $form;
}
function crud_data_crud_form_validate($form, &$form_state) {

$name = $form_state['values']['name'];
global $users;
$error=FALSE;

if (empty($name)) {
form_set_error("erorr",t("Please enter your Name. Here"));
$error=TRUE;
}
if(strlen($name) < 6){
form_set_error("Please Enter atleast 6 character Label.");
$error=TRUE;
}
}
function crud_data_crud_form_submit($form, $form_state) {
    global $user;
    $name = $form_state['values']['name'];
    // Implement DB Insert
    db_insert('my_friends')
    ->fields(array('fr_name', 'uid'))
    ->values(array(
      'fr_name' => $name,
      'uid' => $user->uid,
    ))
    ->execute();
      drupal_set_message("successfully saved Your Friend " . $name );
}
/**
 * Implements hook_theme_registry_alter().
 */
function crud_data_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'crud_data');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}
